export const Users = [
  {
    id:1,
    profilePicture: "profileImgs/1.jpg",
    username: "Mo Saeed",
  },
  {
    id:2,
    profilePicture: "profileImgs/2.jpg",
    username: "Janell Shrum",
  },
  {
    id:3,
    profilePicture: "profileImgs/3.jpg",
    username: "Alex Durden",
  },
  {
    id:4,
    profilePicture: "profileImgs/4.png",
    username: "Dora Hawks",
  },
  {
    id:5,
    profilePicture: "profileImgs/5.gif",
    username: "Thomas Holden",
  },
  {
    id:6,
    profilePicture: "profileImgs/6.jpg",
    username: "Shirley Beauchamp",
  },
  {
    id:7,
    profilePicture: "profileImgs/7.jpg",
    username: "Travis Bennett",
  }
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "postImgs/1.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "postImgs/2.png",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "postImgs/3.png",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "postImgs/4.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "postImgs/5.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "postImgs/1.jpg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "postImgs/2.png",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "postImgs/3.png",
    date: "3 days ago",
    userId: 4,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "postImgs/4.jpg",
    date: "5 days ago",
    userId:2,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "postImgs/5.jpg",
    date: "1 week ago",
    userId: 1,
    like: 104,
    comment: 12,
  },
];